title: "benr.me"
description: "Ben’s notes, projects, and experiments."
url: "https://benr.me"
baseurl: ""          # keep empty for a root site
theme: minima

author:
  name: "Ben Rohrbaugh"
  email: ""

# <- THIS drives the top nav everywhere
header_pages:
  - index.md
  - posts.md
  - projects.md
  - about.md
  - codes.md

minima:
  social_links:
    github: benror4
    x: benror4

show_excerpts: true
markdown: kramdown
plugins:
  - jekyll-seo-tag
